Animated_Antonio_Belpaese_indexed_til:
.incbin "gfx/personajes/Animated_Antonio_Belpaese_indexed.pic"
Animated_Antonio_Belpaese_indexed_tilend:

Animated_Antonio_Belpaese_indexed_pal:
.incbin "gfx/personajes/Animated_Antonio_Belpaese_indexed.pal"
Animated_Antonio_Belpaese_indexed_palend:

