// Exported by gfx4snes 
#ifndef Mad_Forest_crop_64x64_indexed_H_
#define Mad_Forest_crop_64x64_indexed_H_

#include <snes.h>

extern unsigned char Mad_Forest_crop_64x64_indexed_til,Mad_Forest_crop_64x64_indexed_tilend;

extern unsigned short Mad_Forest_crop_64x64_indexed_map,Mad_Forest_crop_64x64_indexed_mapend;

extern unsigned char Mad_Forest_crop_64x64_indexed_pal,Mad_Forest_crop_64x64_indexed_palend;

#endif

